# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.listView1 = QtWidgets.QListView(self.widget_2)
        self.listView1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listView1.setObjectName("listView1")
        self.verticalLayout_8.addWidget(self.listView1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.display = QtWidgets.QLabel(self.widget_5)
        self.display.setText("")
        self.display.setAlignment(QtCore.Qt.AlignCenter)
        self.display.setObjectName("display")
        self.verticalLayout_7.addWidget(self.display)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_13 = QtWidgets.QWidget(self.widget_3)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_7)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.widget_9 = QtWidgets.QWidget(self.widget_7)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_info = QtWidgets.QCheckBox(self.widget_10)
        self.btn_info.setAutoExclusive(False)
        self.btn_info.setObjectName("btn_info")
        self.verticalLayout_5.addWidget(self.btn_info)
        self.btn_noninfo = QtWidgets.QCheckBox(self.widget_10)
        self.btn_noninfo.setAutoExclusive(False)
        self.btn_noninfo.setObjectName("btn_noninfo")
        self.verticalLayout_5.addWidget(self.btn_noninfo)
        self.horizontalLayout_3.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_100 = QtWidgets.QCheckBox(self.widget_11)
        self.btn_100.setAutoExclusive(False)
        self.btn_100.setObjectName("btn_100")
        self.gridLayout.addWidget(self.btn_100, 1, 1, 1, 1)
        self.btn_25 = QtWidgets.QCheckBox(self.widget_11)
        self.btn_25.setAutoExclusive(False)
        self.btn_25.setObjectName("btn_25")
        self.gridLayout.addWidget(self.btn_25, 0, 0, 1, 1)
        self.btn_50 = QtWidgets.QCheckBox(self.widget_11)
        self.btn_50.setAutoExclusive(False)
        self.btn_50.setObjectName("btn_50")
        self.gridLayout.addWidget(self.btn_50, 0, 1, 1, 1)
        self.btn_75 = QtWidgets.QCheckBox(self.widget_11)
        self.btn_75.setAutoExclusive(False)
        self.btn_75.setObjectName("btn_75")
        self.gridLayout.addWidget(self.btn_75, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget_11)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_8)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.widget_12 = QtWidgets.QWidget(self.widget_8)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_blur = QtWidgets.QCheckBox(self.widget_12)
        self.btn_blur.setAutoExclusive(False)
        self.btn_blur.setObjectName("btn_blur")
        self.horizontalLayout.addWidget(self.btn_blur)
        self.btn_over = QtWidgets.QCheckBox(self.widget_12)
        self.btn_over.setAutoExclusive(False)
        self.btn_over.setObjectName("btn_over")
        self.horizontalLayout.addWidget(self.btn_over)
        self.btn_dark = QtWidgets.QCheckBox(self.widget_12)
        self.btn_dark.setAutoExclusive(False)
        self.btn_dark.setObjectName("btn_dark")
        self.horizontalLayout.addWidget(self.btn_dark)
        self.btn_fluid = QtWidgets.QCheckBox(self.widget_12)
        self.btn_fluid.setAutoExclusive(False)
        self.btn_fluid.setObjectName("btn_fluid")
        self.horizontalLayout.addWidget(self.btn_fluid)
        self.verticalLayout_6.addWidget(self.widget_12)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.horizontalLayout_4.addWidget(self.widget_6)
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_back = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout_10.addWidget(self.btn_back)
        self.btn_next = QtWidgets.QPushButton(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_next.sizePolicy().hasHeightForWidth())
        self.btn_next.setSizePolicy(sizePolicy)
        self.btn_next.setObjectName("btn_next")
        self.verticalLayout_10.addWidget(self.btn_next)
        self.horizontalLayout_4.addWidget(self.widget_14)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.listView2 = QtWidgets.QListView(self.widget_4)
        self.listView2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listView2.setObjectName("listView2")
        self.verticalLayout_9.addWidget(self.listView2)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.menuFile.addAction(self.actionOpen_folder)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Noise Images"))
        self.label.setText(_translate("MainWindow", "Score"))
        self.btn_info.setText(_translate("MainWindow", "Informative"))
        self.btn_noninfo.setText(_translate("MainWindow", "Non-Informative"))
        self.btn_100.setText(_translate("MainWindow", "100%"))
        self.btn_25.setText(_translate("MainWindow", "25%"))
        self.btn_50.setText(_translate("MainWindow", "50%"))
        self.btn_75.setText(_translate("MainWindow", "75%"))
        self.label_2.setText(_translate("MainWindow", "Clean content with noise"))
        self.btn_blur.setText(_translate("MainWindow", "Blur"))
        self.btn_over.setText(_translate("MainWindow", "Overexposure"))
        self.btn_dark.setText(_translate("MainWindow", "Dark"))
        self.btn_fluid.setText(_translate("MainWindow", "Foam/Fluid"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
        self.btn_back.setShortcut(_translate("MainWindow", "Left"))
        self.btn_next.setText(_translate("MainWindow", "Next"))
        self.btn_next.setShortcut(_translate("MainWindow", "Right"))
        self.label_4.setText(_translate("MainWindow", "Clean Images"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_folder.setText(_translate("MainWindow", "Open folder"))
        self.actionOpen_folder.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
